// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQ-kT8DQg4XGBvgoQCvsuhTA-mXRJtVQ',
    appId: '1:830787228544:web:1210777cdd99cefddae765',
    messagingSenderId: '830787228544',
    projectId: 'skillpay-project',
    authDomain: 'skillpay-project.firebaseapp.com',
    storageBucket: 'skillpay-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrL9j2lYW0fSlvqtD3tOSH9RZXvqZOY1U',
    appId: '1:830787228544:android:c528b798462c079bdae765',
    messagingSenderId: '830787228544',
    projectId: 'skillpay-project',
    storageBucket: 'skillpay-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkuMQlrIm6MWuoJUnhXIrgABZ2wgpKv4',
    appId: '1:830787228544:ios:476bab41456d18a5dae765',
    messagingSenderId: '830787228544',
    projectId: 'skillpay-project',
    storageBucket: 'skillpay-project.appspot.com',
    iosClientId: '830787228544-g6ggfe1rug5ldio40eeomc65lsp419d7.apps.googleusercontent.com',
    iosBundleId: 'com.skillPay.first',
  );
}
